services:
  db:
    image: postgis/postgis:16-3.4
    container_name: yucatan_dw
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: yucatan_dw
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d yucatan_dw"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: ./api
    container_name: yucatan_api
    environment:
      DB_URL: postgresql+psycopg2://admin:admin123@db:5432/yucatan_dw
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 5s
      timeout: 5s
      retries: 10

  dashboard:
    build: ./dashboard
    container_name: yucatan_dashboard
    environment:
      API_URL: http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      api:
        condition: service_healthy

  airflow-db:
    image: postgres:16
    container_name: yucatan_airflow_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: airflow
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d airflow"]
      interval: 5s
      timeout: 5s
      retries: 10

  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    container_name: yucatan_airflow
    command: standalone
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin:admin123@airflow-db:5432/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin123
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags:ro
      - ./src:/opt/airflow/src:ro
      - ./sql:/opt/airflow/sql:ro
    depends_on:
      airflow-db:
        condition: service_healthy
      db:
        condition: service_healthy

volumes:
  pgdata:
  airflow_pgdata: